template:
  name: go
  env:
    LD_RELEASE_GO_IMPORT_PATH: gopkg.in/launchdarkly/go-jsonstream.v1
  skip: # skip build/test in release for now, because Releaser doesn't have a new enough version of Go
    - build
    - test

releasableBranches:
  - name: v1

publications:
  - url: https://pkg.go.dev/gopkg.in/launchdarkly/go-jsonstream.v1
    description: documentation
