version: 2

jobs:
  - docker:
      image: golang:1.18-buster
    template:
      name: go

branches:
  - name: v3
  - name: v2
  - name: v1

publications:
  - url: https://pkg.go.dev/github.com/launchdarkly/go-jsonstream/v3
    description: documentation
